#!/usr/bin/env bash
#nitrogen --restore &

bspc rule -a --one-shot "Teamspeak 3:ts3client_linux_amd64" desktop=^4 follow=false
bspc rule -a discord desktop=^4

#auto-start things
sh ~/.config/polybar/launch.sh &
dunst &
picom -CGb --blur-background &
nm-applet &
wal -R -q
#source colors
. "${HOME}/.cache/wal/colors.sh"
gwe --hide-window &
teamspeak3 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#enable desktop notifications
bspc rule -a Dunst layer='above'
#fix autistic origin issue
bspc rule -a "origin.exe" state=floating
#fix steam friends
bspc config external_rules_command /home/papu/scripts/bspwm_ex_rules/steam_friends.sh

bspc rule -a "sdlgame" state=floating
