#!/usr/bin/env bash
picom -CGb & #CG removes shadows and b daemonizes
#nitrogen --restore &
sh $HOME/.config/polybar/launch.sh &
nm-applet &
xss-lock i3lock-fancy-rapid 10 pixel &
wal -R -q
sh $HOME/.config/polybar/launch.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#enable desktop notifications
bspc rule -a Dunst layer='above'
#fix autistic origin issue
bspc rule -a "origin.exe" state=floating
#fix steam friends
bspc config external_rules_command /home/papu/scripts/bspwm_ex_rules/steam_friends.sh
